# Configuration for GNN v6 FINAL - Publication Ready Target
# ===========================================================
# Goal: Achieve F1 > 0.58 AND Preference Accuracy > 0.60
#
# Strategy learned from experiments:
# - Dot mode is ESSENTIAL for preference (concat fails)
# - Need alpha >= 0.3 to maintain turnover performance
# - Hard negative mining (0.85) is critical
# - Extended training helps both tasks

seed: 42
device: auto

data:
  graph_path: data/processed/hetero_graph.pt
  triples_path: data/processed/preference_triples.pt
  scaler_path: data/processed/feature_scaler.pkl

model:
  hidden_dim: 128
  num_layers: 2
  heads: 4
  dropout: 0.2
  use_layernorm: true

training:
  weight_decay: 0.0005
  grad_clip: 1.0

  # Stage 1: Solid pre-training
  stage1:
    epochs: 150
    patience: 20
    lr: 0.001

  # Stage 2: Balanced optimization
  stage2:
    epochs: 200
    patience: 30
    lr: 0.0004           # Moderate LR for stability

    # ⚖️ Lean toward turnover (to maintain F1) while keeping preference strong
    alpha: 0.35          # Turnover: 35%
    beta: 0.65           # Preference: 65%

    # Strong hard negative mining
    hard_ratio: 0.85
    cache_size: 10
    update_freq: 5

    freeze_layers: 0

loss:
  # Balanced focal loss
  turnover:
    loss_type: focal
    alpha: 0.32          # Moderate positive class emphasis
    gamma: 2.3           # Moderate hard sample focus
    pos_weight: null

  # Preference ranking with adaptive margin
  preference:
    loss_type: adaptive_margin
    margin: 0.9          # Moderate initial margin
    max_margin: 2.8
    margin_growth: 0.09
    ranking_weight: 0.12
    hard_negative_weight: 1.8  # Moderate weighting

  # DOT MODE (proven essential for preference)
  preference_head:
    hidden_dim: 128
    dropout: 0.3
    mode: dot

logging:
  save_dir: outputs/hetero_v6_final
